# Generated by Django 6.0.6 on 2026-07-26 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
    ]
