# Generated by Django 6.0.6 on 2026-07-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
