# Generated by Django 6.0.6 on 2026-07-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_remove_course_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='modules',
            field=models.IntegerField(null=True),
        ),
    ]
