# Generated by Django 6.0.6 on 2026-08-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_payment_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='course',
        ),
        migrations.AddField(
            model_name='payment',
            name='learning_mode',
            field=models.CharField(default='Offline', max_length=20),
        ),
    ]
