# Generated by Django 6.0.6 on 2026-08-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_payment_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='learning_mode',
            field=models.CharField(max_length=20),
        ),
    ]
