# Generated by Django 6.0.6 on 2026-08-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_payment_created_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(default=1000),
        ),
    ]
